using System.Collections.Generic;
using System.Linq;

namespace RingtoneComposer.Core
{
    public class FrequenceRepository
    {
        private readonly List<NoteFrequence> noteFrequenceArray = new List<NoteFrequence>
        {
            //new NoteFrequence(Pitchs.C,Scales.Zero,65.41),
            //new NoteFrequence(Pitchs.Csharp,Scales.Zero,69.3),
            //new NoteFrequence(Pitchs.D,Scales.Zero,73.42),
            //new NoteFrequence(Pitchs.Dsharp,Scales.Zero,77.78),
            //new NoteFrequence(Pitchs.E,Scales.Zero,82.41),
            //new NoteFrequence(Pitchs.F,Scales.Zero,87.31),
            //new NoteFrequence(Pitchs.Fsharp,Scales.Zero,92.5),
            //new NoteFrequence(Pitchs.G,Scales.Zero,98),
            //new NoteFrequence(Pitchs.Gsharp,Scales.Zero,103.83),
            //new NoteFrequence(Pitchs.A,Scales.Zero,110),
            //new NoteFrequence(Pitchs.Asharp,Scales.Zero,116.54),
            //new NoteFrequence(Pitchs.B,Scales.Zero,123.47),
            //new NoteFrequence(Pitchs.C,Scales.One,65.41),
            //new NoteFrequence(Pitchs.Csharp,Scales.One,69.3),
            //new NoteFrequence(Pitchs.D,Scales.One,73.42),
            //new NoteFrequence(Pitchs.Dsharp,Scales.One,77.78),
            //new NoteFrequence(Pitchs.E,Scales.One,82.41),
            //new NoteFrequence(Pitchs.F,Scales.One,87.31),
            //new NoteFrequence(Pitchs.Fsharp,Scales.One,92.5),
            //new NoteFrequence(Pitchs.G,Scales.One,98),
            //new NoteFrequence(Pitchs.Gsharp,Scales.One,103.83),
            //new NoteFrequence(Pitchs.A,Scales.One,110),
            //new NoteFrequence(Pitchs.Asharp,Scales.One,116.54),
            //new NoteFrequence(Pitchs.B,Scales.One,123.47),
            //new NoteFrequence(Pitchs.C,Scales.Two,130.81),
            //new NoteFrequence(Pitchs.Csharp,Scales.Two,138.59),
            //new NoteFrequence(Pitchs.D,Scales.Two,146.83),
            //new NoteFrequence(Pitchs.Dsharp,Scales.Two,155.56),
            //new NoteFrequence(Pitchs.E,Scales.Two,164.81),
            //new NoteFrequence(Pitchs.F,Scales.Two,174.61),
            //new NoteFrequence(Pitchs.Fsharp,Scales.Two,185),
            //new NoteFrequence(Pitchs.G,Scales.Two,196),
            //new NoteFrequence(Pitchs.Gsharp,Scales.Two,207.65),
            //new NoteFrequence(Pitchs.A,Scales.Two,220),
            //new NoteFrequence(Pitchs.Asharp,Scales.Two,233.08),
            //new NoteFrequence(Pitchs.B,Scales.Two,246.94),
            //new NoteFrequence(Pitchs.C,Scales.Three,261.63),
            //new NoteFrequence(Pitchs.Csharp,Scales.Three,277.18),
            //new NoteFrequence(Pitchs.D,Scales.Three,293.66),
            //new NoteFrequence(Pitchs.Dsharp,Scales.Three,311.13),
            //new NoteFrequence(Pitchs.E,Scales.Three,329.63),
            //new NoteFrequence(Pitchs.F,Scales.Three,349.23),
            //new NoteFrequence(Pitchs.Fsharp,Scales.Three,369.99),
            //new NoteFrequence(Pitchs.G,Scales.Three,392),
            //new NoteFrequence(Pitchs.Gsharp,Scales.Three,415.3),
            //new NoteFrequence(Pitchs.A,Scales.Three,440),
            //new NoteFrequence(Pitchs.Asharp,Scales.Three,466.16),
            //new NoteFrequence(Pitchs.B,Scales.Three,493.88),
            new NoteFrequence(Pitchs.C,Scales.Four,523.25),
            new NoteFrequence(Pitchs.Csharp,Scales.Four,554.37),
            new NoteFrequence(Pitchs.D,Scales.Four,587.33),
            new NoteFrequence(Pitchs.Dsharp,Scales.Four,622.25),
            new NoteFrequence(Pitchs.E,Scales.Four,659.26),
            new NoteFrequence(Pitchs.F,Scales.Four,698.46),
            new NoteFrequence(Pitchs.Fsharp,Scales.Four,739.99),
            new NoteFrequence(Pitchs.G,Scales.Four,783.99),
            new NoteFrequence(Pitchs.Gsharp,Scales.Four,830.61),
            new NoteFrequence(Pitchs.A,Scales.Four,880),
            new NoteFrequence(Pitchs.Asharp,Scales.Four,932.33),
            new NoteFrequence(Pitchs.B,Scales.Four,987.77),
            new NoteFrequence(Pitchs.C,Scales.Five,1046.5),
            new NoteFrequence(Pitchs.Csharp,Scales.Five,1108.73),
            new NoteFrequence(Pitchs.D,Scales.Five,1174.66),
            new NoteFrequence(Pitchs.Dsharp,Scales.Five,1244.51),
            new NoteFrequence(Pitchs.E,Scales.Five,1318.51),
            new NoteFrequence(Pitchs.F,Scales.Five,1396.91),
            new NoteFrequence(Pitchs.Fsharp,Scales.Five,1479.98),
            new NoteFrequence(Pitchs.G,Scales.Five,1567.98),
            new NoteFrequence(Pitchs.Gsharp,Scales.Five,1661.22),
            new NoteFrequence(Pitchs.A,Scales.Five,1760),
            new NoteFrequence(Pitchs.Asharp,Scales.Five,1864.66),
            new NoteFrequence(Pitchs.B,Scales.Five,1975.53),
            new NoteFrequence(Pitchs.C,Scales.Six,2093),
            new NoteFrequence(Pitchs.Csharp,Scales.Six,2217.46),
            new NoteFrequence(Pitchs.D,Scales.Six,2349.32),
            new NoteFrequence(Pitchs.Dsharp,Scales.Six,2489.02),
            new NoteFrequence(Pitchs.E,Scales.Six,2637.02),
            new NoteFrequence(Pitchs.F,Scales.Six,2793.83),
            new NoteFrequence(Pitchs.Fsharp,Scales.Six,2959.96),
            new NoteFrequence(Pitchs.G,Scales.Six,3135.96),
            new NoteFrequence(Pitchs.Gsharp,Scales.Six,3322.44),
            new NoteFrequence(Pitchs.A,Scales.Six,3520),
            new NoteFrequence(Pitchs.Asharp,Scales.Six,3729.31),
            new NoteFrequence(Pitchs.B,Scales.Six,3951.07),
            new NoteFrequence(Pitchs.C,Scales.Seven,4186.01),
            new NoteFrequence(Pitchs.Csharp,Scales.Seven,4434.92),
            new NoteFrequence(Pitchs.D,Scales.Seven,4698.64),
            new NoteFrequence(Pitchs.Dsharp,Scales.Seven,4978.03),
            new NoteFrequence(Pitchs.E,Scales.Seven,5274.04),
            new NoteFrequence(Pitchs.F,Scales.Seven,5587.65),
            new NoteFrequence(Pitchs.Fsharp,Scales.Seven,5919.91),
            new NoteFrequence(Pitchs.G,Scales.Seven,6271.93),
            new NoteFrequence(Pitchs.Gsharp,Scales.Seven,6644.88),
            new NoteFrequence(Pitchs.A,Scales.Seven,7040),
            new NoteFrequence(Pitchs.Asharp,Scales.Seven,7458.62),
            new NoteFrequence(Pitchs.B,Scales.Seven,7902.13)
        };

        public double this[Pitchs note, Scales octave]
        {
            get
            {
                return noteFrequenceArray.Where(w => w.Pitch.Equals(note) && w.Scale.Equals(octave)).Select(s => s.Frequence).FirstOrDefault();
            }
        }
    }
}
