using System.Collections.Generic;
using System.Linq;

namespace RingtoneComposer.Core
{
    public class FrequenceRepository
    {
        private readonly List<NoteFrequence> noteFrequenceArray = new List<NoteFrequence>
        {
            //new NoteFrequence(Pitches.C,Scales.Zero,65.41),
            //new NoteFrequence(Pitches.Csharp,Scales.Zero,69.3),
            //new NoteFrequence(Pitches.D,Scales.Zero,73.42),
            //new NoteFrequence(Pitches.Dsharp,Scales.Zero,77.78),
            //new NoteFrequence(Pitches.E,Scales.Zero,82.41),
            //new NoteFrequence(Pitches.F,Scales.Zero,87.31),
            //new NoteFrequence(Pitches.Fsharp,Scales.Zero,92.5),
            //new NoteFrequence(Pitches.G,Scales.Zero,98),
            //new NoteFrequence(Pitches.Gsharp,Scales.Zero,103.83),
            //new NoteFrequence(Pitches.A,Scales.Zero,110),
            //new NoteFrequence(Pitches.Asharp,Scales.Zero,116.54),
            //new NoteFrequence(Pitches.B,Scales.Zero,123.47),
            //new NoteFrequence(Pitches.C,Scales.One,65.41),
            //new NoteFrequence(Pitches.Csharp,Scales.One,69.3),
            //new NoteFrequence(Pitches.D,Scales.One,73.42),
            //new NoteFrequence(Pitches.Dsharp,Scales.One,77.78),
            //new NoteFrequence(Pitches.E,Scales.One,82.41),
            //new NoteFrequence(Pitches.F,Scales.One,87.31),
            //new NoteFrequence(Pitches.Fsharp,Scales.One,92.5),
            //new NoteFrequence(Pitches.G,Scales.One,98),
            //new NoteFrequence(Pitches.Gsharp,Scales.One,103.83),
            //new NoteFrequence(Pitches.A,Scales.One,110),
            //new NoteFrequence(Pitches.Asharp,Scales.One,116.54),
            //new NoteFrequence(Pitches.B,Scales.One,123.47),
            //new NoteFrequence(Pitches.C,Scales.Two,130.81),
            //new NoteFrequence(Pitches.Csharp,Scales.Two,138.59),
            //new NoteFrequence(Pitches.D,Scales.Two,146.83),
            //new NoteFrequence(Pitches.Dsharp,Scales.Two,155.56),
            //new NoteFrequence(Pitches.E,Scales.Two,164.81),
            //new NoteFrequence(Pitches.F,Scales.Two,174.61),
            //new NoteFrequence(Pitches.Fsharp,Scales.Two,185),
            //new NoteFrequence(Pitches.G,Scales.Two,196),
            //new NoteFrequence(Pitches.Gsharp,Scales.Two,207.65),
            //new NoteFrequence(Pitches.A,Scales.Two,220),
            //new NoteFrequence(Pitches.Asharp,Scales.Two,233.08),
            //new NoteFrequence(Pitches.B,Scales.Two,246.94),
            //new NoteFrequence(Pitches.C,Scales.Three,261.63),
            //new NoteFrequence(Pitches.Csharp,Scales.Three,277.18),
            //new NoteFrequence(Pitches.D,Scales.Three,293.66),
            //new NoteFrequence(Pitches.Dsharp,Scales.Three,311.13),
            //new NoteFrequence(Pitches.E,Scales.Three,329.63),
            //new NoteFrequence(Pitches.F,Scales.Three,349.23),
            //new NoteFrequence(Pitches.Fsharp,Scales.Three,369.99),
            //new NoteFrequence(Pitches.G,Scales.Three,392),
            //new NoteFrequence(Pitches.Gsharp,Scales.Three,415.3),
            //new NoteFrequence(Pitches.A,Scales.Three,440),
            //new NoteFrequence(Pitches.Asharp,Scales.Three,466.16),
            //new NoteFrequence(Pitches.B,Scales.Three,493.88),
            new NoteFrequence(Pitches.C,Scales.Four,523.25),
            new NoteFrequence(Pitches.Csharp,Scales.Four,554.37),
            new NoteFrequence(Pitches.D,Scales.Four,587.33),
            new NoteFrequence(Pitches.Dsharp,Scales.Four,622.25),
            new NoteFrequence(Pitches.E,Scales.Four,659.26),
            new NoteFrequence(Pitches.F,Scales.Four,698.46),
            new NoteFrequence(Pitches.Fsharp,Scales.Four,739.99),
            new NoteFrequence(Pitches.G,Scales.Four,783.99),
            new NoteFrequence(Pitches.Gsharp,Scales.Four,830.61),
            new NoteFrequence(Pitches.A,Scales.Four,880),
            new NoteFrequence(Pitches.Asharp,Scales.Four,932.33),
            new NoteFrequence(Pitches.B,Scales.Four,987.77),
            new NoteFrequence(Pitches.C,Scales.Five,1046.5),
            new NoteFrequence(Pitches.Csharp,Scales.Five,1108.73),
            new NoteFrequence(Pitches.D,Scales.Five,1174.66),
            new NoteFrequence(Pitches.Dsharp,Scales.Five,1244.51),
            new NoteFrequence(Pitches.E,Scales.Five,1318.51),
            new NoteFrequence(Pitches.F,Scales.Five,1396.91),
            new NoteFrequence(Pitches.Fsharp,Scales.Five,1479.98),
            new NoteFrequence(Pitches.G,Scales.Five,1567.98),
            new NoteFrequence(Pitches.Gsharp,Scales.Five,1661.22),
            new NoteFrequence(Pitches.A,Scales.Five,1760),
            new NoteFrequence(Pitches.Asharp,Scales.Five,1864.66),
            new NoteFrequence(Pitches.B,Scales.Five,1975.53),
            new NoteFrequence(Pitches.C,Scales.Six,2093),
            new NoteFrequence(Pitches.Csharp,Scales.Six,2217.46),
            new NoteFrequence(Pitches.D,Scales.Six,2349.32),
            new NoteFrequence(Pitches.Dsharp,Scales.Six,2489.02),
            new NoteFrequence(Pitches.E,Scales.Six,2637.02),
            new NoteFrequence(Pitches.F,Scales.Six,2793.83),
            new NoteFrequence(Pitches.Fsharp,Scales.Six,2959.96),
            new NoteFrequence(Pitches.G,Scales.Six,3135.96),
            new NoteFrequence(Pitches.Gsharp,Scales.Six,3322.44),
            new NoteFrequence(Pitches.A,Scales.Six,3520),
            new NoteFrequence(Pitches.Asharp,Scales.Six,3729.31),
            new NoteFrequence(Pitches.B,Scales.Six,3951.07),
            new NoteFrequence(Pitches.C,Scales.Seven,4186.01),
            new NoteFrequence(Pitches.Csharp,Scales.Seven,4434.92),
            new NoteFrequence(Pitches.D,Scales.Seven,4698.64),
            new NoteFrequence(Pitches.Dsharp,Scales.Seven,4978.03),
            new NoteFrequence(Pitches.E,Scales.Seven,5274.04),
            new NoteFrequence(Pitches.F,Scales.Seven,5587.65),
            new NoteFrequence(Pitches.Fsharp,Scales.Seven,5919.91),
            new NoteFrequence(Pitches.G,Scales.Seven,6271.93),
            new NoteFrequence(Pitches.Gsharp,Scales.Seven,6644.88),
            new NoteFrequence(Pitches.A,Scales.Seven,7040),
            new NoteFrequence(Pitches.Asharp,Scales.Seven,7458.62),
            new NoteFrequence(Pitches.B,Scales.Seven,7902.13)
        };

        public double this[Pitches note, Scales octave]
        {
            get
            {
                return noteFrequenceArray.Where(w => w.Pitch.Equals(note) && w.Scale.Equals(octave)).Select(s => s.Frequence).FirstOrDefault();
            }
        }
    }
}
